version: 2.1  
 
jobs: 
  docker_tests: 
      docker:
            - image: circleci/python:3.9.6-buster 
      steps: 
        - checkout 
        - run: 
            name: "Enable Script execution"
            no_output_timeout: 60m 
            command: bash spring.sh 
 
  windows_tests: 
      docker:
            - image: circleci/python:3.9.6-buster 
      steps: 
        - checkout 
        - run: 
            name: "Enable Script execution" 
            no_output_timeout: 60m
            command: bash spring.sh 
 
  mac_tests: 
      docker:
            - image: circleci/python:3.9.6-buster 
      steps: 
        - checkout 
        - run: 
            name: "Enable Script execution" 
            no_output_timeout: 60m
            command: bash spring.sh  
             
workflows: 
  version: 2 
  testing:  
    jobs: 
      - docker_tests 
      - windows_tests 
      - mac_tests